language: java
jdk: oraclejdk8
before_install:
  - mkdir -p ~/.m2
  - echo "<settings><server><id>magnolia.forge.snapshots</id><username>${USERNAME}</username><password>${PASSWORD}</password></server></settings>" > ~/.m2/settings.xml
script:
  - mvn clean deploy
cache:
  directories:
    - "~/.m2/repository"
